name: Test

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{secrets.SSH_HOST }} | sed 's/./& /g'
      - run: echo ${{ secrets.SSH_USER }} | sed 's/./& /g'
      - run: echo ${{ secrets.SSH_PORT }} | sed 's/./& /g'
      - run: echo ${{ secrets.SSH_KEY }} | sed 's/./& /g'
